### ISSUE TITLE
The [TYPE] option for command SCAN is not avaliable until redis `6.0+`

### ISSUE THREAD

**Issue by landybird** [laixintao/iredis#315]
As documents [the-type-option](https://redis.io/commands/scan#the-type-option)  said, you can use option `TYPE` to ask `SCAN` to only return objects that match a given type as of `version 6.0 `.

But the [commands.json](https://github.com/laixintao/iredis/blob/master/iredis/data/commands.json) marked it avaliable  since `2.8.0`. And then there always is a  `syntax error`.

**Comment by laixintao** [comment]
Sorry about that.

But the commands.json is actually from official docs: https://github.com/antirez/redis-doc/blob/10ca7242a10a5c460cba5bdcc3a61bb80e5ac744/commands.json#L3657

`since` means "since which version, this command is available in Redis", any changes for later versions are not included.

Maybe we display the bottom hint based on redis-server version is the ideal way to display, but that required iredis has some kind of version system, completions, syntax, hints, docs all need to based on that versioning system, which is pretty complicated. So I decided to support with latest Redis only.

You need to keep in mind what's not available in your Redis if you use an older version. Sorry again.

**Comment by laixintao** [comment]
Hi @landybird I think I will stick with the latest version of redis. Going to close this issue, feel free to reopen if you have futher questions :)
