### ISSUE TITLE
Create Conda recipe

### ISSUE THREAD

**Issue by aymericbeaumet** [laixintao/iredis#444]
Hello @laixintao,

Not really an issue, but I have created a Conda recipe for this CLI. See: https://github.com/conda-forge/staged-recipes/pull/19991.

Do you give your permission to be marked as a maintainer for this recipe?

**Comment by laixintao** [comment]
Hi, thanks for doing this recipe!

Sorry, I don't quite understand what this means. I hope that I only need to maintain this repo (iredis source code), and don't want to pay much attention to maintaining different packaging systems like ubuntu/brew etc.

So my question is if I comment, does this mean that I need to maintain this conda recipe? If so, I rather hope that I don't need to do that, but I am totally fine that you list only yourself as this conda maintainer.

Of course, if you met any issue of iredis code or dependencies with the packaging work, I am glad to help, like this one: https://github.com/laixintao/iredis/issues/415

**Comment by laixintao** [comment]
But if the comment only confirms that I maintain iredis instead of conda cecipe, then no problem, I can comment. ;D

**Comment by aymericbeaumet** [comment]
Being a maintainer basically means bumping the version number and updating the sha256 when a new release is shipped. It would be easier if you were also a maintainer, but I'll try to pay attention to your release from time to time to bump the recipe :)

I've removed yourself from the recipe maintainers for now 👍

**Comment by laixintao** [comment]
Yes thank you very much for packaging this @aymericbeaumet 

the issue is, I don't have that much attention to maintain for different packages.

some package manager like brew or debian has some kind of version watch: https://git.progress-linux.org/users/daniel.baumann/debian/packages/iredis/tree/debian/watch , basically if the github's release page got a new version they will be notified. I am not sure if conda has similar features.

:D

**Comment by aymericbeaumet** [comment]
I'm not sure Conda has this option (couldn't find it). In the meantime the package has been released :) https://github.com/conda-forge/iredis-feedstock
